language: erlang
branches:
        only:
                - master
notifications:
        email: mongoose-im@erlang-solutions.com
otp_release:
        - 17.5
        - 17.4
        - 17.3
        - R16B03-1
        - R16B02
        - R16B01
script:
        - make && make dialyzer && make test
after_script:
        - if [ -s dialyzer/error.log ]; then cat dialyzer/error.log; fi
