language: erlang
branches:
        only:
                - master
notifications:
        email: mongoose-im@erlang-solutions.com
otp_release:
        - 19.0
        - 18.3
        - 17.5
script:
        - make && make dialyzer && make test
after_script:
        - if [ -s dialyzer/error.log ]; then cat dialyzer/error.log; fi

after_success:
        - make coverage-report
