language: erlang
branches:
        only:
                - master
notifications:
        email: mongoose-im@erlang-solutions.com
otp_release:
        - 19.0
        - 18.3
        - 17.5
install:
        - make
script:
        - make test
        - make dialyzer

after_success:
        - make coverage-report
